[package]
name = "remote_monitor"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.29.0"
serde_json = "1.0.140"
tokio = { version = "1.0", features = ["full"] }
reqwest = { version = "0.11", features = ["json"] }
anyhow = "1.0"