[package]
name = "rcpu"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.7"
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
thiserror = "2.0.12"
libc = "0.2.174"
serde_json = "1.0.140"
